name: chart-challenge-23-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - toolz
  - matplotlib
  - pandas
  - partd
  - bokeh
  - geopandas
  - plotly
  - dataretrieval
  - fiona
  - shapely
  - pyproj>=2.0
  - rtree
  - rasterio
  - gdal
  - scipy
  - rasterstats
  - jupyter
  - ipython
  - ipykernel
  - xarray
  - pip
  - pip:
    - git+https://github.com/aleaf/gis-utils.git
