---
title: "When is drought?"
author: "Althea Archer"
date: "2023-03-10"
output: html_document
---



## Set up

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(warning = FALSE)
```



Define libraries here. 

```{r libraries, warning=FALSE, message=FALSE}
# Load libraries
library(tidyverse) # includes ggplot
library(readr) # best for reading and writing csvs

library(sbtools)
library(lubridate)
library(sf)
library(spData)

# These are used for the layout of the viz
library(cowplot) # for laying out the final plot
library(sysfonts) # for text editing
library(showtext) # for adding in google fonts
library(magick) # for adding logo
```



## Load files


```{r load}
# Add your code here
# Load drought properties data from ScienceBase
#authenticate_sb() (username includes email address)
# Drought Properties - 7day window - 1921-2020 dataset
drought21_properties_7d_file <- "in/Drought_Properties_jd_07d_wndw_1921.csv"
if(!file.exists(drought21_properties_7d_file)){ # if files don't exist, download
  sbtools::item_file_download(sb_id = "62f463c5d34eacf5397395d9",
                              names = "Drought_Properties_jd_07d_wndw.csv",
                              destinations =  "in/Drought_Properties_jd_07d_wndw_1921.csv",
                              overwrite_file = FALSE)
}
temp_1921 <- readr::read_csv(drought21_properties_7d_file) 

# Drought Properties - 7day window - 1951-2020 dataset
drought51_properties_7d_file <- "in/Drought_Properties_jd_07d_wndw_1951.csv"
if(!file.exists(drought51_properties_7d_file)){ # if files don't exist, download
  sbtools::item_file_download(sb_id = "627974ccd34e8d45aa6e3c81",
                              names = "Drought_Properties_jd_07d_wndw.csv",
                              destinations =  "in/Drought_Properties_jd_07d_wndw_1951.csv",
                              overwrite_file = FALSE)
}
temp_1951 <- readr::read_csv(drought51_properties_7d_file) 

# Drought Properties - 7day window - 1981-2020 dataset
drought81_properties_7d_file <- "in/Drought_Properties_jd_07d_wndw_81.csv"
if(!file.exists(drought81_properties_7d_file)){ # if files don't exist, download
  sbtools::item_file_download(sb_id = "62f475abd34eacf5397395e8",
                              names = "Drought_Properties_jd_07d_wndw.csv",
                              destinations =  "in/Drought_Properties_jd_07d_wndw_81.csv",
                              overwrite_file = FALSE)
}
temp_1981 <- readr::read_csv(drought81_properties_7d_file) 


file_in_metadata <- "in/study_watersheds_metadata.csv"
if(!file.exists(file_in_metadata)){ # if files don't exist, download
  sbtools::item_file_download(sb_id = "62793493d34e8d45aa6e3ba9",
                              names = "study_watersheds_metadata.csv",
                              destinations = file_in_metadata,
                              overwrite_file = F)
}
metadata <- readr::read_csv(file_in_metadata, show_col_types = FALSE) |>
  select(StaID, STANAME, DRAIN_SQKM, HUC02, LAT_GAGE, LNG_GAGE, STATE,
         national_1981, national_1951, national_1921, HCDN_2009)


```

## Get data ready for plotting
  

### Spatial mapping data

```{r spatial}
# Download US State boundaries as sf object
states_sf <- spData::us_states
# add in state names, too
st_crosswalk <- data.frame(NAME = state.name,
                           STATE = state.abb)
# Merge in CASC info
states_CASC <- states_sf |>
  mutate("CASC" = case_when(NAME %in% c("Minnesota", "Iowa", "Missouri", 
                                       "Wisconsin", "Illinois", "Indiana", 
                                       "Michigan", "Ohio") ~ "Midwest",
                          NAME %in% c("Montana", "Wyoming", "Colorado", "North Dakota", 
                                       "South Dakota", "Nebraska", "Kansas") ~ "North Central",
                          NAME %in% c("Maine", "New Hampshire", "Vermont", "Massachusetts", 
                                       "Connecticut", "Rhode Island",
                                       "New York", "New Jersey", "Pennsylvania", 
                                       "Delaware", "Maryland", "West Virginia", 
                                       "Virginia", "Kentucky", "District of Columbia") ~ "Northeast",
                          NAME %in% c("Washington", "Oregon", "Idaho") ~ "Northwest",
                          NAME %in% c("New Mexico", "Texas", 
                                      "Oklahoma", "Louisiana") ~ "South Central",
                          NAME %in% c("North Carolina", "South Carolina", "Georgia", "Alabama", 
                                       "Mississippi", "Florida", "Tennessee", 
                                       "Arkansas") ~ "Southeast",
                          NAME %in% c("Arizona",
                                       "Utah", "Nevada") ~ "Southwest",
                          NAME == "California" ~ "California",
                          TRUE ~ "not sorted")) |>
  left_join(st_crosswalk, by = "NAME")

# convert id to CASC for mapping just regions to make them look "exploded"
mapping_data_regions <- states_CASC |>
  group_by(CASC) |>
  summarise(id = unique(CASC))

# CASC names 
CASC_names <- unique(states_CASC$CASC)
```
  
### Prepping data for when is drought


```{r processing_timing}
# Select appropriate threshold (here 2%)
df_1921 <- temp_1921 |> 
  # Join metadata 
  left_join(metadata, by = "StaID") |>
  # Select 2% threshold
  filter(threshold == 2) |>
  mutate(year = lubridate::year(start)) |>
  # remove couple from 2020 (incomplete year)
  filter(year < 2020)

# Select appropriate threshold (here 2%)
df_1951 <- temp_1951 |> 
  # Join metadata 
  left_join(metadata, by = "StaID") |>
  # Select 2% threshold
  filter(threshold == 2) |>
  mutate(year = lubridate::year(start)) |>
  # remove couple from 2020 (incomplete year)
  filter(year < 2020) |>
  # remove redundant records from 1921 data
  filter(! national_1921)

# Select appropriate threshold (here 2%)
df_1981 <- temp_1981 |> 
  # Join metadata 
  left_join(metadata, by = "StaID") |>
  # Select 2% threshold
  filter(threshold == 2) |>
  mutate(year = lubridate::year(start)) |>
  # remove couple from 2020 (incomplete year)
  filter(year < 2020) |>
  # remove redundant records from 1921 data
  filter(! national_1921,
         ! national_1951)

droughts_2pct <- bind_rows(df_1921, df_1951, df_1981)

droughts_100perYear <- droughts_2pct |>
  slice_max(order_by = severity,
            n = 2000)


droughts_100_join_CASC <- droughts_100perYear |>
  # Join with CASCs
  mutate(CASC = case_when(STATE %in% c("MN", "IA", "MO", "WI", "IL", "IN", "MI", "OH") ~ "Midwest",
                          STATE %in% c("MT", "WY", "CO", "ND", "SD", "NE", "KS") ~ "North Central",
                          STATE %in% c("ME", "NH", "VT", "MA", "CT", "RI", "DC",
                                       "NY", "NJ", "PA", "DE", "MD", "WV", "VA", "KY") ~ "Northeast",
                          STATE %in% c("WA", "OR", "ID") ~ "Northwest",
                          STATE %in% c("NM", "TX", "OK", "LA") ~ "South Central",
                          STATE %in% c("NC", "SC", "GA", "AL", "MS", "FL", "TN", "AR") ~ "Southeast",
                          STATE %in% c("AZ", "UT", "NV") ~ "Southwest",
                          STATE %in% "CA" ~ "California",
                          TRUE ~ "not sorted"),
         north_south = case_when(CASC %in% c("Northwest", "North Central", "Midwest", "Northeast") ~ "North",
                                 TRUE ~ "South"),
         CASC = factor(CASC, levels = c("California", "Southwest", "South Central", "Southeast",
                                        "Northeast", "Midwest", "North Central", "Northwest")))

# Number of 100 most severe droughts by year in each CASC
table(droughts_100_join_CASC$CASC)
table(droughts_100_join_CASC$north_south)
length(table(droughts_100_join_CASC$STATE))

# Make long
droughts_long <- droughts_100_join_CASC |>
  uncount(duration, .id = "day_of_drought") |>
  # for future munging
  mutate(drought_date = start + day_of_drought -1,
         decade = year(floor_date(start, years(10))),
         year = year(drought_date),
         jd = yday(drought_date),
         drought_day_noYr = format(as.Date(drought_date), "%m-%d"),
         drought_day_fakeYr = as.Date(sprintf("1999-%s", drought_day_noYr), "%Y-%m-%d")) |>
  # make sure they're sorted by date
  arrange(start) |>
  # remove unneeded fields
  select(-threshold, -previous_end, -days_since_previous_drought,
         -has_the_potential_to_be_impacted_by_missing_values) 


```






## Set up global plotting settings

```{r plotting}
# Load some custom fonts and set some custom settings
font_legend <- "Source Sans Pro"
supporting_font <- "Source Sans Pro"
annotation_font <- "Permanent Marker"
sysfonts::font_add_google("Source Sans Pro")
sysfonts::font_add_google("Permanent Marker")
showtext::showtext_opts(dpi = 300, regular.wt = 200, bold.wt = 700)
showtext::showtext_auto(enable = TRUE)

# Font sizes
title_size <- 50
support_size <- 20

# Define colors
background_color = "#FFFAF4"
font_color = "#431c5d"
base_color = "#431c5d"#"#B4E4FF"  #"#FF6D60"#"#9384D1"#8BD0CF"#"#73A9AD"
pop_color = "#431c5d"#"#B4E4FF" #"#FFD966"#"#FF6D60"#36A19F"#"#73A9AD"#"#e05915"
viridis_palette = "inferno"
viridis_begin = 0.15
viridis_end = 0.85
viridis_direction = -1

# The background canvas for your viz
canvas <- grid::rectGrob(
  x = 0, y = 0, 
  width = 16, height = 9,
  gp = grid::gpar(fill = background_color, alpha = 1, col = background_color)
)

# Load in USGS logo (also a black logo available)
usgs_logo <- magick::image_read("../usgs_logo_black.png") |>
  magick::image_colorize(opacity = 100, color = font_color)



month_labels <- tibble(
  drought_day_fakeYr = as.Date(c("1999-01-03", sprintf("1999-%s-01", 
                                       c("02", "03", "04", "05", "06",
                                         "07", "08", "09", "10", "11", "12")))),
  y_CONUS = 8100,
  label = c("J", "F", "M", "A", "M", "J", "J", "A", "S", "O", "N", "D")
)

month_labels_CASC <- tibble(
  drought_day_fakeYr = rep(month_labels$drought_day_fakeYr, 
                           each = length(CASC_names)),
  y_region = 2000,
  label = rep(month_labels$label,
              each = length(CASC_names)),
  CASC = rep(CASC_names, nrow(month_labels))
)

```

### Making the "when is drought" viz

```{r map}
(map_plot <- ggplot(data = states_CASC) +
    geom_sf(fill = base_color, color = background_color, linewidth = 0.4) +
    geom_sf(data = mapping_data_regions, color = background_color, fill = NA, linewidth = 1.5)+
    geom_segment(aes(x = -125, xend = -127, # northwest
                     y = 50, yend = 52), 
                 arrow = arrow(length = unit(0.65, "lines")),
                 color = base_color, linewidth = 1.3, lineend = "round")+
    geom_segment(aes(x = -101, xend = -101, # north central
                     y = 50, yend = 52), 
                 arrow = arrow(length = unit(0.65, "lines")),
                 color = base_color, linewidth = 1.3, lineend = "round")+
    geom_segment(aes(x = -81, xend = -70, # midwest
                     y = 48, yend = 52), 
                 arrow = arrow(length = unit(0.65, "lines")),
                 color = base_color, linewidth = 1.3, lineend = "round")+
    geom_segment(aes(x = -74, xend = -70, # northeast
                     y = 39, yend = 39), 
                 arrow = arrow(length = unit(0.65, "lines")),
                 color = base_color, linewidth = 1.3, lineend = "round")+
    geom_segment(aes(x = -124, xend = -127, # california
                     y = 37, yend = 37), 
                 arrow = arrow(length = unit(0.65, "lines")),
                 color = base_color, linewidth = 1.3, lineend = "round")+
    geom_segment(aes(x = -113, xend = -127, # southwest
                     y = 30, yend = 24), 
                 arrow = arrow(length = unit(0.65, "lines")),
                 color = base_color, linewidth = 1.3, lineend = "round")+
    geom_segment(aes(x = -101, xend = -101, #south central
                     y = 26, yend = 24), 
                 arrow = arrow(length = unit(0.65, "lines")),
                 color = base_color, linewidth = 1.3, lineend = "round")+
    geom_segment(aes(x = -80, xend = -70, #southeast
                     y = 30, yend = 24), 
                 arrow = arrow(length = unit(0.65, "lines")),
                 color = base_color, linewidth = 1.3, lineend = "round")+
   theme_void() +
    theme(legend.position = "none")
)
```



```{r plot_test}
(CASC_season_plot <- ggplot(data = droughts_long, 
                     aes(x = drought_day_fakeYr)) +
   geom_histogram(aes(fill = sprintf("%ss", decade), group = desc(decade)),
                  boundary = 0, bins = 36)+
   geom_text(data = month_labels_CASC,  
              aes(x = drought_day_fakeYr, y = y_region, label = label),
             family = supporting_font, #fontface = "bold", 
             size = 4.9, color = font_color,
             vjust = 0.5, hjust = 0.5) +
   facet_wrap(~ CASC)+
   scale_x_date(breaks = "3 month", date_labels = "%b", 
                limits = as.Date(c("1999-01-01", "1999-12-31")),
                expand = c(-0.015,0))+
   labs(fill = "Decade")+
   coord_polar()+
   theme_minimal()+
   ylim(c(0, 2500))+
   scale_fill_viridis_d(begin = viridis_begin, end = viridis_end, 
                        direction = viridis_direction, option = viridis_palette,
                        guide = guide_legend(reverse = TRUE) )+
   theme(legend.title = element_blank(),
         legend.text = element_text(size = support_size,
                                    family = supporting_font),
         legend.key.height = unit(1, "cm"),
         legend.key.width = unit(1, "cm"))
 )

legend_seasons <- cowplot::get_legend(CASC_season_plot)
```


```{r overallPlot}
(month_label_chart <- ggplot(data = droughts_long, 
                     aes(x = drought_day_fakeYr)) +
   geom_text(data = month_labels,  
              aes(x = drought_day_fakeYr, y = y_CONUS, label = label),
             family = supporting_font, #fontface = "bold", 
             size = 4.9, color = font_color,
             vjust = 0.5, hjust = 0.5) +
   scale_x_date(breaks = "3 month", date_labels = "%b", 
                limits = as.Date(c("1998-12-30", "2000-01-03")),
                expand = c(-0.0141,0))+
   coord_polar()+
   theme_void()
 )

(full_plot <- ggplot(data = droughts_long, 
                     aes(x = drought_day_fakeYr)) +
   geom_histogram(aes(fill = decade, group = desc(decade)), boundary = 0, bins = 36)+
   # geom_text(data = month_labels, #|> filter(! drought_day_fakeYr == "1999-01-01"), 
   #            aes(x = drought_day_fakeYr, y = y_CONUS, label = label),
   #           family = supporting_font, #fontface = "bold", 
   #           size = 4.7, color = font_color,
   #           vjust = 0.5, hjust = 0.5) +
   scale_x_date(breaks = "3 month", date_labels = "%b", 
                limits = as.Date(c("1998-12-30", "2000-01-03")),
                expand = c(-0.0141,0))+
   labs(fill = "Decade")+
   coord_polar()+
   theme_minimal()+
   ylim(c(-1000, 7900))+
   scale_fill_viridis_c(begin = viridis_begin, end = viridis_end, 
                        direction = viridis_direction, option = viridis_palette)+
   theme(legend.position = "none",
          axis.text = element_blank(),
          axis.title = element_blank())
 )
```

```{r casc_seasons}
# Chart settings
Ymargin <-  0.04
Xmargin <- 0.03

# CASC Plots
Xbase <- 1-Xmargin # from right
Ybase <- Ymargin*2 # from bottom
Yjitter <- (0.83 - 2*Ymargin)/3
Xjitter <- (0.64 - 2*Xmargin)/3

# Function to make regional plots
draw_CASC_plots <- map(1:length(CASC_names), function(x){
  # create temporary plot
  plot_temp <- droughts_long |>
    filter(CASC == CASC_names[x]) |> 
    ggplot(aes(x = drought_day_fakeYr)) +
    facet_wrap(~ CASC)+
   geom_text(data = month_labels_CASC |> filter(CASC == CASC_names[x]),  
              aes(x = drought_day_fakeYr, y = y_region, label = label),
             family = supporting_font, #fontface = "bold", 
             size = 4, color = font_color,
             vjust = 0.5, hjust = 0.5) +
    geom_histogram(aes(fill = decade, group = desc(decade)), 
                   boundary = 0, bins = 36)+
   scale_x_date(breaks = "3 month", date_labels = "%b", 
                limits = as.Date(c("1998-12-30", "2000-01-03")),
                expand = c(-0.0141,0))+
    coord_polar()+
    theme_minimal()+
    ylim(c(-500, 2000))+
    scale_fill_viridis_c(begin = viridis_begin, end = viridis_end, 
                        direction = viridis_direction, option = viridis_palette)+
    theme(legend.position = "none",
          strip.text = element_text(size = support_size, color = font_color,
                                    family = supporting_font, face = "bold"),
          axis.text = element_blank(),
          axis.title = element_blank())
  
  if(CASC_names[x] %in% c("Southwest", "Southeast", "South Central")){
    Y_position <- Ybase
  } else if(CASC_names[x] %in% c("California", "Northeast")){
    Y_position <- Ybase + Yjitter
  } else {
    Y_position <- Ybase + 2*Yjitter
  }
  
  if(CASC_names[x] %in% c("Northwest", "California", "Southwest")){
    X_position <- Xbase - (2*Xjitter)
  } else if(CASC_names[x] %in% c("North Central", "South Central")){
    X_position <- Xbase - Xjitter
  } else {
    X_position <- Xbase
  } 
  
  draw_plot(plot_temp,
            x = X_position,
            y = Y_position,
            hjust = 1,
            height = Yjitter,
            width = Xjitter)
})
```


#### Produce final plot


```{r cowplot, fig.width = 16, fig.height = 9}
ggdraw(ylim = c(0,1), # 0-1 scale makes it easy to place viz items on canvas
       xlim = c(0,1)) +
  # a background
  draw_grob(canvas,
            x = 0, y = 1,
            height = 9, width = 16,
            hjust = 0, vjust = 1) +
  # the main plot
  draw_CASC_plots +
  draw_grob(legend_seasons,
            y = -.03,
            x = -0.12)+
  draw_plot(map_plot,
            y = 0.45,
            x = 0.822,
            hjust = 1,
            vjust = 0.5, 
            width = 0.25) +
  draw_plot(full_plot,
            y = 0.455,
            x = 0.1755 ,
            width = 0.3,
            height = 0.53,
            vjust = 0.5, hjust = 0.5)+
  draw_plot(month_label_chart,
            y = 0.455,
            x = 0.1755 ,
            width = 0.8,
            height = 1.1,
            vjust = 0.5, hjust = 0.5)+
  # explainer text
  draw_label("Severe streamflow drought events were defined with 2% variable 7-day thresholds (Hammond et al. 2022; doi.org/10.1029/2022WR031930).\nChart by Althea A. Archer. Data based on streamgage records from 3,196 gages assessed from 1920 to 2020: doi.org/10.5066/P92FAASD.",
             fontfamily = supporting_font,
             x = 1 - Xmargin,   
             y = Ymargin,
             size = 14,
             hjust = 1,
             vjust = 0,
             color = font_color)+
  # Title
  draw_label("When do streamflow droughts occur?",
             x = Xmargin,
             y = 1 - Ymargin,
             hjust = 0,
             vjust = 1,
             lineheight = 1.0,
             fontfamily = annotation_font,
             color = font_color,
             size = title_size,
             fontface = "bold") +
  
  # Title
  draw_label("These are the 2000 most severe streamflow droughts at gages from 1920 to 2020 by day of year, decade, and region.",
             x = Xmargin,
             y = 1 - 3*Ymargin ,
             hjust = 0,
             vjust = 1,
             lineheight = 1.0,
             fontfamily = supporting_font,
             color = font_color,
             size = support_size) +
  # Label for CONUS
  draw_label("Conterminous United States\n(Lower 48)",
             x = 0.17, 
             y = 0.786,
             hjust = 0.5,
             vjust = 0.5,
             fontface = "bold",
             fontfamily = supporting_font,
             color = font_color,
             size = support_size) +
  # Add logo
  draw_image(usgs_logo, 
             x = Xmargin,
             y = Ymargin,
             width = 0.1, 
             hjust = 0, vjust = 0, 
             halign = 0, valign = 0)+
  # Y-axis explainer
  # geom_segment(aes(x = 0.1763, xend = 0.1763, 
  #                  y = 0.455, yend = 0.649), 
  #              arrow = grid::arrow(length = unit(0.75, 'lines')),
  #              color = background_color,
  #              lineend = 'round',
  #              linewidth = 2)+  
  geom_segment(aes(x = 0.1763, xend = 0.1763, 
                   y = 0.455, yend = 0.649), 
               arrow = grid::arrow(length = unit(0.75, 'lines')),
               color = "white",
               lineend = 'round',
               linewidth = 1.5)+
  draw_text("# of\ndroughts",
            x = 0.17,
            y = 0.535,
            color = "white", size = support_size, family = annotation_font,
            hjust = 1)+
  # Facts
  # X-axis explainer
    geom_curve(aes(xend = 0.285, 
                   x = 0.1763,
                   yend = 0.47, 
                   y = 0.66),
             arrow = grid::arrow(length = unit(0.75, 'lines')),
             curvature = -0.40,
             angle = -88,
             color = pop_color,
             lineend = 'round',
             linewidth = 1.5)+
  draw_text("Day of\n   year",
            x = 0.24,
            y = 0.67,
            color = pop_color, size = support_size, family = annotation_font,
            hjust = 0)


# Save the final image in Twitter's 16 by 9 format
# !! Use format for saving with the date of your prompt: 
#         YYYYMMDD_prompt_name ()
# e.g. `20230101_part-to-whole-cnell.png`
ggsave(filename = "out/20230711_16by9_whenDrought_aaarcher.png", 
       width = 16, height = 9, dpi = 300)
```

```{r casc_seasonsIG}
# Chart settings
Ymargin <-  0.03
Xmargin <- 0.03

# CASC Plots
Xbase <- 1-Xmargin # from right
Ybase <- Ymargin*3 # from bottom
Yjitter <- (0.83 - 2*Ymargin)/3
Xjitter <- (1 - 2*Xmargin)/3

# Function to make regional plots
draw_CASC_plots <- map(1:length(CASC_names), function(x){
  # create temporary plot
  plot_temp <- droughts_long |>
    filter(CASC == CASC_names[x]) |> 
    ggplot(aes(x = drought_day_fakeYr)) +
    facet_wrap(~ CASC)+
   geom_text(data = month_labels_CASC |> filter(CASC == CASC_names[x]),  
              aes(x = drought_day_fakeYr, y = y_region, label = label),
             family = supporting_font, #fontface = "bold", 
             size = 4, color = font_color,
             vjust = 0.5, hjust = 0.5) +
    geom_histogram(aes(fill = decade, group = desc(decade)), 
                   boundary = 0, bins = 36)+
   scale_x_date(breaks = "3 month", date_labels = "%b", 
                limits = as.Date(c("1998-12-30", "2000-01-03")),
                expand = c(-0.0141,0))+
    coord_polar()+
    theme_minimal()+
    ylim(c(-500, 2000))+
    scale_fill_viridis_c(begin = viridis_begin, end = viridis_end, 
                        direction = viridis_direction, option = viridis_palette)+
    theme(legend.position = "none",
          strip.text = element_text(size = support_size, color = font_color,
                                    family = supporting_font, face = "bold"),
          axis.text = element_blank(),
          axis.title = element_blank())
  
  if(CASC_names[x] %in% c("Southwest", "Southeast", "South Central")){
    Y_position <- Ybase
  } else if(CASC_names[x] %in% c("California", "Northeast")){
    Y_position <- Ybase + Yjitter
  } else {
    Y_position <- Ybase + 2*Yjitter
  }
  
  if(CASC_names[x] %in% c("Northwest", "California", "Southwest")){
    X_position <- Xbase - (2*Xjitter)
  } else if(CASC_names[x] %in% c("North Central", "South Central")){
    X_position <- Xbase - Xjitter
  } else {
    X_position <- Xbase
  } 
  
  draw_plot(plot_temp,
            x = X_position,
            y = Y_position,
            hjust = 1,
            height = Yjitter,
            width = Xjitter)
})
```

```{r cowplot-a, fig.width = 9, fig.height = 9}

title_size = 30
support_size = 15
ggdraw(ylim = c(0,1), # 0-1 scale makes it easy to place viz items on canvas
       xlim = c(0,1)) +
  # a background
  draw_grob(canvas,
            x = 0, y = 1,
            height = 9, width = 9,
            hjust = 0, vjust = 1) +
  draw_grob(legend_seasons,
            y = -0.0,
            x = -0.4)+
  draw_plot(full_plot,
            y = 0.42,
            x = 0.6 ,
            width = 0.75,
            height = 0.75,
            vjust = 0.5, hjust = 0.5)+
  draw_plot(month_label_chart,
            y = 0.42,
            x = 0.6 ,
            width = 1.58,
            height = 1.58,
            vjust = 0.5, hjust = 0.5)+
  # explainer text
  draw_label("Chart by Althea A. Archer.\nData based on streamgage records from 3,196 gages assessed from 1920 to 2020: doi.org/10.5066/P92FAASD.\nDrought events were defined by 2% variable 7-day thresholds (Hammond et al. 2022; doi.org/10.1029/2022WR031930).",
             fontfamily = supporting_font,
             x = 1 - Xmargin,   
             y = 0.03,
             size = 10,
             hjust = 1,
             vjust = 0,
             color = font_color)+
  # Title
  draw_label("When do streamflow droughts occur?",
             x = Xmargin,
             y = 1 - Ymargin,
             hjust = 0,
             vjust = 1,
             lineheight = 1.0,
             fontfamily = annotation_font,
             color = font_color,
             size = title_size,
             fontface = "bold") +
  
  # Title
  draw_label("These are the 2000 most severe streamflow droughts at gages from 1920 to 2020\nby day of year, region, and decade.",
             x = Xmargin,
             y = 1 - 2.5*Ymargin ,
             hjust = 0,
             vjust = 1,
             lineheight = 1.0,
             fontfamily = supporting_font,
             color = font_color,
             size = support_size) +
  # Label for CONUS
  draw_label("Conterminous United States (Lower 48)",
             x = 0.5, 
             y = 0.8,
             hjust = 0.5,
             vjust = 0.5,
             fontface = "bold",
             fontfamily = supporting_font,
             color = font_color,
             size = support_size) +
  # Add logo
  draw_image(usgs_logo, 
             x = Xmargin,
             y = 0.03,
             width = 0.15, 
             hjust = 0, vjust = 0, 
             halign = 0, valign = 0)+
  # Y-axis explainer
  # geom_segment(aes(x = 0.602, xend = 0.602, 
  #                  y = 0.42, yend = 0.70), 
  #              arrow = grid::arrow(length = unit(0.75, 'lines')),
  #              color = background_color,
  #              lineend = 'round',
  #              linewidth = 2)+  
  geom_segment(aes(x = 0.602, xend = 0.602, 
                   y = 0.42, yend = 0.70), 
               arrow = grid::arrow(length = unit(0.75, 'lines')),
               color = "white",
               lineend = 'round',
               linewidth = 1.5)+
  draw_text("# of\ndroughts",
            x = 0.58,
            y = 0.62,
            color = "white", size = support_size, family = annotation_font,
            hjust = 1)+
  # Facts
  # X-axis explainer
    geom_curve(aes(xend = 0.89, 
                   x = 0.602,
                   yend = 0.47, 
                   y = 0.72),
             arrow = grid::arrow(length = unit(0.75, 'lines')),
             curvature = -0.40,
             angle = -88,
             color = pop_color,
             lineend = 'round',
             linewidth = 1.5)+
  draw_text("Day of\n   year",
            x = 0.84,
            y = 0.68,
            color = pop_color, size = support_size, family = annotation_font,
            hjust = 0)


# Save the final image in Twitter's 16 by 9 format
# !! Use format for saving with the date of your prompt: 
#         YYYYMMDD_prompt_name ()
# e.g. `20230101_part-to-whole-cnell.png`
ggsave(filename = "out/20230711_1to1a_whenDrought_aaarcher.png", 
       width = 9, height = 9, dpi = 300)
```



```{r cowplot-b, fig.width = 9, fig.height = 9}

ggdraw(ylim = c(0,1), # 0-1 scale makes it easy to place viz items on canvas
       xlim = c(0,1)) +
  # a background
  draw_grob(canvas,
            x = 0, y = 1,
            height = 9, width = 9,
            hjust = 0, vjust = 1) +
  # the main plot
  draw_CASC_plots +
  draw_plot(map_plot,
            y = 0.48,
            x = 0.52,
            hjust = 0.5,
            vjust = 0.5, 
            width = 0.36) +
  # explainer text
  draw_label("Chart by Althea A. Archer.\nData based on streamgage records from 3,196 gages assessed from 1920 to 2020: doi.org/10.5066/P92FAASD.\nDrought events were defined by 2% variable 7-day thresholds (Hammond et al. 2022; doi.org/10.1029/2022WR031930).",
             fontfamily = supporting_font,
             x = 1 - Xmargin,   
             y = 0.03,
             size = 10,
             hjust = 1,
             vjust = 0,
             color = font_color)+
  # Title
  draw_label("When do streamflow droughts occur?",
             x = Xmargin,
             y = 1 - Ymargin,
             hjust = 0,
             vjust = 1,
             lineheight = 1.0,
             fontfamily = annotation_font,
             color = font_color,
             size = title_size,
             fontface = "bold") +
  
  # Title
  draw_label("These are the 2000 most severe streamflow droughts at gages from 1920 to 2020\nby day of year, region, and decade.",
             x = Xmargin,
             y = 1 - 2.5*Ymargin ,
             hjust = 0,
             vjust = 1,
             lineheight = 1.0,
             fontfamily = supporting_font,
             color = font_color,
             size = support_size) +
  # Add logo
  draw_image(usgs_logo, 
             x = Xmargin,
             y = 0.03,
             width = 0.15, 
             hjust = 0, vjust = 0, 
             halign = 0, valign = 0)


# Save the final image in Twitter's 16 by 9 format
# !! Use format for saving with the date of your prompt: 
#         YYYYMMDD_prompt_name ()
# e.g. `20230101_part-to-whole-cnell.png`
ggsave(filename = "out/20230711_1to1b_whenDrought_aaarcher.png", 
       width = 9, height = 9, dpi = 300)
```

## Supporting information

### Key takeaways of this viz (1-2 sentences each)

1. Key takeaways here

### Data source(s)

Data sources here.

